import { useState, type Dispatch, type SetStateAction } from 'react';
import { classifyUnassigned, type Data } from './model';
export function BatchClassification({ data, words, update, close }: { data: Data; words: string[]; update: Dispatch<SetStateAction<Data>>; close: () => void }) {
  const [checked, setChecked] = useState<string[]>([]);
  const options = data.categoryOrder.filter(category => category !== '未分類');
  const [category, setCategory] = useState(options[0] ?? '');
  const available = words.filter(word => (data.categories[word] ?? '未分類') === '未分類');
  const selected = checked.filter(word => available.includes(word));
  function toggle(word: string) { setChecked(previous => previous.includes(word) ? previous.filter(item => item !== word) : [...previous, word]); }
  return <section className="category-settings batch-classification"><div className="list-heading"><h2>未分類をまとめて分類</h2><button onClick={close}>閉じる</button></div><p className="muted">キーワードを押して選択し、下の枠で確認して分類します。</p><div className="batch-tools"><button onClick={() => setChecked(available)}>未分類をすべて選択</button><button onClick={() => setChecked([])}>選択解除</button><span>{selected.length} / {available.length}個選択</span></div><div className="batch-picker" aria-label="未分類のキーワード">{available.map(word => <button key={word} className="batch-chip" aria-pressed={selected.includes(word)} onClick={() => toggle(word)}>{selected.includes(word) && <span aria-hidden="true">✓ </span>}*{word}</button>)}{!available.length && <p>未分類のキーワードはありません。</p>}</div><form className="batch-selection" onSubmit={event => { event.preventDefault(); if (!selected.length || !options.includes(category)) return; update(previous => classifyUnassigned(previous, selected, category)); setChecked([]); if (selected.length === available.length) close(); }}><h3>選択内容 <span>{selected.length}個</span></h3><div className="selected-chips" aria-label="選択したキーワード">{selected.map(word => <button type="button" key={word} className="batch-chip" onClick={() => toggle(word)} aria-label={`*${word}の選択を外す`}>*{word} <span aria-hidden="true">×</span></button>)}{!selected.length && <p>まだ選択していません。</p>}</div><div className="batch-tools"><label>分類先 <select value={category} onChange={event => setCategory(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></label><button className="primary" disabled={!selected.length || !options.includes(category)}>まとめて設定</button></div>{!options.length && <p>分類設定で分類を追加してください。</p>}</form></section>;
}
