import type { Data } from './model';
import { keywords, personWords, changeKeywordCategory } from './model';
import { KeywordConnections, ConnectionPicker } from './KeywordConnections';
type Props = { data: Data; selected: string | null; editing: string | null; linkSource: string | null; keywordIds: string[]; setData: (data: Data) => void; selectKeyword: (word: string) => void; setRenaming: (value: boolean) => void; setMerging: (value: boolean) => void; setLinkSource: (value: string | null) => void; showKeywordList: boolean; setShowKeywordList: (value: boolean) => void; showBoardMemos: boolean; setShowBoardMemos: (value: boolean) => void; view: string };
export function KeywordContext({data, selected, editing, linkSource, keywordIds, setData, selectKeyword, setRenaming, setMerging, setLinkSource, showKeywordList, setShowKeywordList, showBoardMemos, setShowBoardMemos, view}: Props) {
 return <div className="context-header" aria-label="選択キーワードとつながり">        {selected && <div className="selection"><div><span className="keyword-kind">キーワード</span><h2>*{selected}</h2><span>{data.notes.filter(note=>keywords(note.text).some(word=>personWords(data,selected).includes(word))).length}件のメモ</span></div><label>分類<select value={data.categories[selected] ?? '未分類'} onChange={event => setData(changeKeywordCategory(data, selected, event.target.value))}>{data.categoryOrder.map(category => <option key={category}>{category}</option>)}</select></label><button onClick={() => setRenaming(true)} disabled={editing !== null || !!linkSource} title={editing !== null ? 'メモの編集を完了してから変更してください' : undefined}>名前を変更</button><button disabled={editing !== null || !!linkSource} onClick={()=>setMerging(true)}>統合</button></div>}
        {linkSource && <ConnectionPicker source={linkSource} words={keywordIds} data={data} update={setData} close={() => setLinkSource(null)}/>}
        {selected && <KeywordConnections word={selected} data={data} update={setData} select={selectKeyword} begin={() => setLinkSource(selected)} isChoosing={!!linkSource}/>}
<div className="organize-switch"><button aria-expanded={showKeywordList} onClick={() => setShowKeywordList(!showKeywordList)}>{showKeywordList ? 'キーワード一覧を隠す' : 'キーワード一覧を表示'}</button>{view === 'board' && <button aria-pressed={showBoardMemos} onClick={() => setShowBoardMemos(!showBoardMemos)}>{showBoardMemos ? '関連メモを隠す' : '関連メモを表示'}</button>}</div></div>;
}
