import './MemoCard.css';
import { Icon } from './Icon';
import './Icon.css';
import { useRef, type ReactNode } from 'react';
import { updateNoteText, moveRelative, type Data, type Note } from './model';
import { KeywordEditor } from './KeywordEditor';
import { TimelineSetting } from './TimelineSetting';
import type { useDragOrder } from './useDragOrder';
import { MemoDialog } from './MemoDialog';
import { useSmallScreen } from './useSmallScreen';
type Props = { data: Data; notes: Note[]; counts: Map<string, number>; view: string; editing: string | null; editText: string; setEditText: (value: string) => void; setEditing: (value: string | null) => void; setData: (data: Data) => void; dragOrder: ReturnType<typeof useDragOrder>; noteIds: string[]; rendered: (text: string) => ReactNode };
export function MemoList({data, notes, counts, view, editing, editText, setEditText, setEditing, setData, dragOrder, noteIds, rendered}: Props) {
 const smallScreen=useSmallScreen();
 const editDrafts=useRef<Record<string,string>>({});
 function closeEdit(){if(editing)editDrafts.current[editing]=editText;setEditing(null);}
 function saveEdit(){if(!editing||!editText.trim())return;setData(updateNoteText(data,editing,editText));delete editDrafts.current[editing];setEditing(null);}
 return <div className="note-list">{smallScreen && editing && <MemoDialog title="メモを編集" value={editText} onChange={setEditText} registered={new Set(counts.keys())} submitLabel="保存" submit={saveEdit} close={closeEdit}/>}{notes.map((note, index) => <article key={note.id} {...(view !== 'notes' && editing !== note.id ? dragOrder.row('notes', note.id) : {})}>{editing !== note.id && <div className="note-card-heading"><div className="note-sort-main">{view !== 'notes' && <button className="drag-handle" aria-label="メモをドラッグして並べ替え" {...dragOrder.handle('notes', note.id)}>⠿</button>}<TimelineSetting note={note} data={data} update={setData}/></div><div className="memo-card-actions">{view !== 'notes' && <div className="memo-move-actions"><button type="button" className="icon-button" aria-label="メモを上へ" title="メモを上へ" disabled={index === 0} onClick={() => setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index - 1].id, false) })}>↑</button><button type="button" className="icon-button" aria-label="メモを下へ" title="メモを下へ" disabled={index === notes.length - 1} onClick={() => setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index + 1].id, true) })}>↓</button></div>}<button type="button" className="icon-button" aria-label="メモを編集" title="メモを編集" onClick={() => { setEditing(note.id); setEditText(editDrafts.current[note.id] ?? note.text); }}><Icon name="edit"/></button><button type="button" className="icon-button" aria-label="メモを削除" title="メモを削除" onClick={() => { if (window.confirm('このメモを削除しますか？')) setData({ ...data, notes: data.notes.filter(item => item.id !== note.id), timeline: Object.fromEntries(Object.entries(data.timeline ?? {}).filter(([id]) => id !== note.id)) }); }}><Icon name="delete"/></button></div></div>}{editing === note.id && !smallScreen ? <form onSubmit={event => { event.preventDefault(); if (!editText.trim()) return; setData(updateNoteText(data, note.id, editText)); setEditing(null); }}><KeywordEditor label="メモを編集" autoFocus value={editText} onChange={setEditText} registered={new Set(counts.keys())}/><div className="actions"><button type="button" onClick={() => setEditing(null)}>キャンセル</button><button className="primary" disabled={!editText.trim()}>保存</button></div></form> : <><div className="note-body">{rendered(note.text)}</div><div className="note-footer"><time dateTime={note.createdAt}>{new Date(note.createdAt).toLocaleString('ja-JP', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time></div></>}</article>)}</div>;
}
