import './MemoCard.css';
import { Icon } from './Icon';
import { ActionMenu } from './ActionMenu';
import './Icon.css';
import type { ReactNode } from 'react';
import type { MemoEditing } from './useMemoEditing';
import { moveRelative, type Data, type Note } from './model';
import { MemoEditForm } from './MemoEditForm';
import { TimelineSetting } from './TimelineSetting';
import type { useDragOrder } from './useDragOrder';
import { useSmallScreen } from './useSmallScreen';
type Props = { data: Data; notes: Note[]; counts: Map<string, number>; view: string; editor: MemoEditing; setData: (data: Data) => void; dragOrder: ReturnType<typeof useDragOrder>; noteIds: string[]; rendered: (text: string) => ReactNode };
export function MemoList({data, notes, counts, view, editor, setData, dragOrder, noteIds, rendered}: Props) {
 const smallScreen=useSmallScreen();
 const {editing}=editor;
 const registered=new Set(counts.keys());
 return <div className="note-list">{smallScreen && editing && <MemoEditForm editor={editor} registered={registered} modal/>}{notes.map((note, index) => <article key={note.id} {...(view !== 'notes' && editing !== note.id ? dragOrder.row('notes', note.id) : {})}>{editing !== note.id && <div className="note-card-heading"><div className="note-sort-main">{view !== 'notes' && <button className="drag-handle" aria-label="メモをドラッグして並べ替え" {...dragOrder.handle('notes', note.id)}>⠿</button>}{view !== 'notes' && <TimelineSetting note={note} data={data} update={setData} disabled={editing !== null}/>}</div><div className="memo-card-actions">{view !== 'notes' && !smallScreen && <div className="memo-move-actions"><button type="button" className="icon-button" aria-label="メモを上へ" title="メモを上へ" disabled={index === 0} onClick={() => setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index - 1].id, false) })}>↑</button><button type="button" className="icon-button" aria-label="メモを下へ" title="メモを下へ" disabled={index === notes.length - 1} onClick={() => setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index + 1].id, true) })}>↓</button></div>}<button type="button" className="icon-button" aria-label="メモを編集" title="メモを編集" disabled={editing !== null} onClick={() => editor.begin(note)}><Icon name="edit"/></button>{smallScreen ? <ActionMenu label="⋯" title="メモの操作">{close => <>{view !== 'notes' && <><button type="button" disabled={index === 0} onClick={() => {close(); setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index - 1].id, false) });}}>上へ移動</button><button type="button" disabled={index === notes.length - 1} onClick={() => {close(); setData({ ...data, noteOrder: moveRelative(noteIds, note.id, notes[index + 1].id, true) });}}>下へ移動</button></>}<button type="button" onClick={() => { if (window.confirm('このメモを削除しますか？')) {close(); setData({ ...data, notes: data.notes.filter(item => item.id !== note.id), timeline: Object.fromEntries(Object.entries(data.timeline ?? {}).filter(([id]) => id !== note.id)) });}}}>メモを削除</button></>}</ActionMenu> : <button type="button" className="icon-button" aria-label="メモを削除" title="メモを削除" onClick={() => { if (window.confirm('このメモを削除しますか？')) setData({ ...data, notes: data.notes.filter(item => item.id !== note.id), timeline: Object.fromEntries(Object.entries(data.timeline ?? {}).filter(([id]) => id !== note.id)) }); }}><Icon name="delete"/></button>}</div></div>}{editing === note.id && !smallScreen ? <MemoEditForm editor={editor} registered={registered} preserveTime={Object.hasOwn(data.timeline ?? {}, note.id)}/> : <><div className="note-body">{rendered(note.text)}</div><div className="note-footer"><time dateTime={note.createdAt}>{new Date(note.createdAt).toLocaleString('ja-JP', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time></div></>}</article>)}</div>;
}
