import { useState } from 'react';
import { noteTimes, addTimelineNotes, type Data } from './model';
export function TimelineBulk({data,update,close}: {data: Data; update: (data: Data) => void; close: () => void}) {
 const candidates=data.notes.filter(note=>!Object.hasOwn(data.timeline ?? {},note.id));
 const [selected,setSelected]=useState<string[]>([]), [times,setTimes]=useState<Record<string,string>>({}), [search,setSearch]=useState('');
 const visible=candidates.filter(note=>note.text.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 function initial(id: string) { const note=candidates.find(note=>note.id===id)!;const options=noteTimes(data,note);return options.length===1?options[0]:''; }
 return <section className="category-settings"><div className="list-heading"><h2>タイムラインにまとめて追加</h2><button onClick={close}>閉じる</button></div><input type="search" aria-label="追加するメモを検索" placeholder="メモを検索" value={search} onChange={event=>setSearch(event.target.value)}/><div className="actions"><button onClick={()=>setSelected(previous=>[...new Set([...previous,...visible.map(note=>note.id)])])}>表示中をすべて選択</button><button onClick={()=>setSelected([])}>選択をクリア</button></div><p>{selected.length}件選択 · 登録済みのメモは除外しています。</p><div className="timeline-bulk-list">{visible.map(note=>{const checked=selected.includes(note.id), options=noteTimes(data,note), time=times[note.id]??initial(note.id);return <article key={note.id}><label className="bulk-note"><input type="checkbox" checked={checked} onChange={event=>setSelected(previous=>event.target.checked?[...previous,note.id]:previous.filter(id=>id!==note.id))}/><span>{note.text}</span></label>{checked && <><label>基準時刻<input type="time" aria-label={`メモ${candidates.indexOf(note)+1}の基準時刻`} value={time} onChange={event=>setTimes(previous=>({...previous,[note.id]:event.target.value}))}/></label><div className="time-candidates">{options.map(value=><button key={value} aria-pressed={time===value} onClick={()=>setTimes(previous=>({...previous,[note.id]:value}))}>{value}</button>)}<button onClick={()=>setTimes(previous=>({...previous,[note.id]:''}))}>時刻不明</button></div>{options.length>1 && !time && <p className="muted">複数の時刻があります。指定しなければ時刻不明で追加します。</p>}</>}</article>;})}</div>{!candidates.length && <p className="muted">追加できるメモはありません。</p>}<p className="muted">検索で隠れた選択も追加します。基準時刻が空欄のメモは時刻不明になります。</p><div className="actions"><button onClick={close}>キャンセル</button><button className="primary" disabled={!selected.length} onClick={()=>{update(addTimelineNotes(data,selected.map(id=>({id,time:(times[id]??initial(id))||null}))));close();}}>{selected.length}件を追加</button></div></section>;
}
